var elementsJson=[
   {   title:'文本输入框',
       icon:'icon-dingdan',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       typeclass:'type-textarea',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'文本输入框',
       isEmpty:false,
       dPlaceh:'',
       isLabelPortrait:"false",
       element:'textarea',
       type:'',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'input输入框',
       icon:'icon-dingdan',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       typeclass:'type-input',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'文本输入框',
       isEmpty:false,
       dPlaceh:'',
       isLabelPortrait:"false",
       element:'input',
       type:'text',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'单选框',
       icon:'icon-danxuan',
       sizeX: 1, minSizeY: 1,
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       typeclass:'type-radio',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'单选框',
       isEmpty:false,
       dPlaceh:'',
       itemlayout:'0',
       isLabelPortrait:"false",
       element:'input',
       type:'radio',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''

   },
   {   title:'复选框',
       icon:'icon-fuxuan',
       sizeX: 1, minSizeY: 1,
       sizeX: 1, sizeY: 1,
       row: null, col: null,
       typeclass:'type-checkbox',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'复选框',
       isEmpty:true,
       itemlayout:'0',
       isLabelPortrait:"false",
       isitemPortrait:'true',
       element:'input',
       type:'checkbox',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'下拉框',
       icon:'icon-xiala',
       sizeX: 1, sizeY: 1,
       row: null, col: null,
       typeclass:'type-select',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'下拉框',
       isEmpty:true,
       isLabelPortrait:"false",
       element:'select',
       type:'',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''

   }, {   title:'日期',
       icon:'icon-rili',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'date',
       typeclass:'type-date',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'日期',
       isEmpty:false,
       tempdateValue:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'时间',
       icon:'icon-iconfonttime',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'time',
       typeclass:'type-time',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'时间',
       isEmpty:false,
       temptimeValue:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''

   },
   {   title:'日期时间',
       icon:'icon-riqishijian',
       minSizeX: 2, minSizeY: 1,
       sizeX: 2, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'datetime',
       typeclass:'type-datetime',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'日期时间',
       isEmpty:false,
       temptimeValue:'',
       tempdateValue:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
 {   title:'隐藏表单',
     icon:'icon-riqishijian',
     minSizeX: 1, minSizeY: 1,
     sizeX: 1, sizeY: 1,
     row:null, col:null,
     element:'input',
     type:'hidden',
     typeclass:'type-datetime',
     isActive:false,
     isReadonly:false,
     label:'',
     type_placeholder:'隐藏表单',
     isEmpty:false,
     temptimeValue:'',
     tempdateValue:'',
     isLabelPortrait:"false",
     elementId:'',
     isDisable:'false',
     isVisible:'true',
     isEditable:'true',
     isReadonly:'false',
     event:null,
     errorMsg:'不能为空！',
     menuCode:'',
     name:'',
     defaultValue:''
 },
   {   title:'数字',
       icon:'icon-shuzi',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'number',
       typeclass:'type-number',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'数字',
       isEmpty:false,
       units:'',
       dPlaceh:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {
       title:'附件',
       icon:'icon-attachment',
       minSizeY:1,minSizeX:2,
       sizeX: 1, sizeY: 2,
       row:null, col:null,
       element:'input',
       type:'file',
       typeclass:'type-attachment',
       isActive:false,
       isReadonly:false,
       label:'',
       isEmpty:true,
       type_placeholder:'附件',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'手机',
       icon:'icon-renminbi',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'tel',
       typeclass:'type-tel',
       isActive:false,
       isReadonly:false,
       label:'',
       itemvalue:'',
       type_placeholder:'手机',
       isEmpty:false,
       dPlaceh:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'办公电话',
       icon:'icon-renminbi',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'officeTel',
       typeclass:'type-officeTel',
       isActive:false,
       isReadonly:false,
       label:'',
       itemvalue:'',
       type_placeholder:'办公电话',
       isEmpty:false,
       dPlaceh:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'邮箱',
       icon:'icon-renminbi',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'email',
       typeclass:'type-email',
       isActive:false,
       isReadonly:false,
       label:'',
       itemvalue:'',
       type_placeholder:'邮箱',
       isEmpty:false,
       dPlaceh:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'密码',
       icon:'icon-renminbi',
       sizeX: 1, sizeY: 1,
       row:null, col:null,
       element:'input',
       type:'password',
       typeclass:'type-password',
       isActive:false,
       isReadonly:false,
       label:'',
       itemvalue:'',
       type_placeholder:'密码',
       isEmpty:false,
       dPlaceh:'',
       isLabelPortrait:"false",
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'只读文本',
       icon:'icon-yan',
       minSizeY:1,minSizeX:2,
       sizeX: 1, sizeY: 2,
       row:null, col:null,
       element:'',
       type:'',
       typeclass:'type-readText',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'',
       isEmpty:false,
       tempValue:'',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {   title:'时长',
       icon:'icon-jishiqi',
       //sizeX:3, sizeY: 3,
       minSizeY:3,minSizeX:3,
       sizeX: 3, sizeY: 3,
       row:null, col:null,
       element:'',
       type:'',
       typeclass:'type-period',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'时长',
       isEmpty:true,
       accuracy:'day',
       starttime:'',
       endtime:'',
       starttimes:'开始时间',
       endtimes:'结束时间',
       timeDifference:0,
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       isReadonly:'false',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:''
   },
   {  title:'三级联动',
       icon:'icon-jishiqi',
       minSizeY:1,
       minSizeX:2,
       sizeX:2,
       sizeY:1,
       row:null,col:null,
       element:'',
       type:'',
       typeclass:'type-ld',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'三级联动',
       isEmpty:true,
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       event:null,
       errorMsg:'wroung',
       menuCode:'sanjiliandong',
       name:'sjld',
       defaultValue:'defaultValue',
       isLabelPortrait:"false"
   },
   {
       title:'按钮组件',
       icon:'icon-dingdan',
       sizeX: 1, sizeY:1,
       minSizeY:1,
       minSizeX:1,
       row:null, col:null,
       typeclass:'type-button',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'按钮组件',
       isEmpty:false,
       Dplaceh:'',
       isLabelPortrait:"false",
       element:'input',
       type:'inputWithButton',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:'',
       units:''
   },
   {
       title:'选择组件',
       icon:'icon-dingdan',
       sizeX: 1, sizeY:1,
       minSizeY:1,
       minSizeX:1,
       row:null, col:null,
       typeclass:'type-button',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'选择组件',
       isEmpty:false,
       Dplaceh:'',
       isLabelPortrait:"false",
       element:'input',
       type:'inputWithSelect',
       elementId:'',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:'',
       units:''
   },

   {
		title:'混合菜单',
		icon:'icon-dingdan',
		sizeX: 2, sizeY:1,
		minSizeY:1,
		minSizeX:1,
		row:null, col:null,
		typeclass:'type-mixmenu',
		isActive:false,
		isReadonly:false,
		label:'',
		type_placeholder:'混合菜单',
		isEmpty:false,
		Dplaceh:'',
		isLabelPortrait:"false",
		element:'',
		type:'',
		elementId:'buttonInput',
		isDisable:'false',
		isVisible:'true',
		isEditable:'true',
		event:null,
		errorMsg:'不能为空！',
		menuCode:'',
		name:'',
		defaultValue:'defaultValue'
   },
   {
       title:'Ueditor',
       icon:'icon-dingdan',
       sizeX: 3, sizeY:7,
       minSizeY:7,
       minSizeX:3,
       row:null, col:null,
       typeclass:'type-ueditor',
       isActive:false,
       isReadonly:false,
       label:'',
       type_placeholder:'Ueditor',
       isEmpty:false,
       Dplaceh:'',
       isLabelPortrait:"false",
       element:'Ueditor',
       type:'',
       elementId:'Ueditor',
       isDisable:'false',
       isVisible:'true',
       isEditable:'true',
       event:null,
       errorMsg:'不能为空！',
       menuCode:'',
       name:'',
       defaultValue:'defaultValue'
   }
];